name: prolif
channels:
  - conda-forge
  - defaults
  - anaconda
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - pandoc
  - pip
  - python
  - rdkit
  - cython
  - nbsphinx
  - networkx
  - recommonmark
  - seaborn
  - sphinx
  - tqdm
  - mdanalysis
  - pip:
    - pyvis
    - py3Dmol

